### curl request
/*
curl --request GET \
 --url "http:/localhost:8085/api/retry?scenario=X"
*/
GET http://localhost:8085/api/retry?scenario=429-503-ok
/*
scenarios: two-fails-then-success, always-fail
- none = always-success
*/






